name: piggywise_child_front
description: "Um MVP para um projeto da disciplina de Desenvolvimento de Produtos."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  agattp:
    git:
      url: git@github.com:anlix-io/agattp.git
      ref: dev

  cupertino_icons: ^1.0.8

  flutter:
    sdk: flutter

  flutter_svg: ^2.0.14
  http: ^1.2.2
  intl: ^0.19.0
  percent_indicator: ^4.2.3
  random_avatar: ^0.0.8

dev_dependencies:
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/piggy1.png
    - assets/images/piggy.svg