name: piggywise_child_front
description: "Um mockup para um projeto da disciplina de Desenvolvimento de Produtos."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  agattp:
    git:
      url: git@github.com:anlix-io/agattp.git
      ref: dev

  cupertino_icons: ^1.0.8

  flutter:
    sdk: flutter

  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/piggy1.png

